Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource types
    Type: String
  VPCCIDR:
    Description: The IP range of our VPC
    Type: String
  PublicSubnet1Cidr:
    Description: The IP range of our VPC
    Type: String
  PublicSubnet2Cidr:
    Description: The IP range of our VPC
    Type: String
  PrivateSubnet1Cidr:
    Description: The IP range of our VPC
    Type: String
  PrivateSubnet2Cidr:
    Description: The IP range of our VPC
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: false
      Tags:
        - Key: Parent
          Value: EnvironmentName

  # Public Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      # The IPv4 CIDR block assigned to the subnet.
      CidrBlock: !Ref PublicSubnet1Cidr
      # Indicates whether instances launched in this subnet receive a public IPv4 address.
      MapPublicIpOnLaunch: true
      # The ID of the VPC the subnet is in.
      VpcId: !Ref VPC
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicSubnet2Cidr
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC

  # Private Subnets
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnet1Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnet2Cidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC

  # Internet Gateway
  IGW:
    Type: AWS::EC2::InternetGateway
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC

  # NAT Gatway
  NAT:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
          - EIP
          - AllocationId
      SubnetId: !Ref PublicSubnet1
  EIP:
    Type: AWS::EC2::EIP

  # Routing tables
  PublicSubnetRoutingTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  PrivateSubnetRoutingTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
